### PR TITLE
more flexible, accept string in exnumerator(when values are atom), as version <1.2

### PR DESCRIPTION
**Pull request by mbenatti**

### CODE REVIEW

**Comment by KamilLelonek** [comment]
Please pull the recent changes from the `master` branch.

**Comment by mbenatti** [comment]
@KamilLelonek 
I think that I overrided your last commit ("code format")
Can you add my changes in your master branch?

**Comment by KamilLelonek** [comment]
Once you pull the changes firstly.

**Comment by mbenatti** [comment]
Something went wrong in my local branch, here I have your commit but I overwritten them,

I will delete this PR

**Pull request closed without merging**
